Repository FHIDev/Fhi.HelseId, pull requests merged in 2025-02, with the labels that each got.

#609 Remove AddHelseIdAuthenticationServicesForApis
  Fhi.HelseId.Api/AuthHeaderHandlerForApi.cs
  Fhi.HelseId.Api/ExtensionMethods/ServiceCollectionExtensions.cs
  Fhi.HelseId.Testframework/NHNTTT/TTTService.cs
Labels: breaking

#610 Do not pack Fhi.TestFramework
  Fhi.HelseId.Testframework/Fhi.TestFramework.csproj
Labels: internal

#614 Remove duplicate NuGet publish
  .github/workflows/Fhi.HelseId.Nuget.yml
Labels: Build

#613 Skip token for allow anonymous attribute
  Fhi.HelseId.Tests/AuthHeaderHandlerTests.cs
  Fhi.HelseId.Web/AuthHeaderHandler.cs
Labels: bug

#616 Remove {class}.{method} from log-messages
  Fhi.HelseId.Api/Handlers/ApiMultiScopeHandler.cs
  Fhi.HelseId.Api/Handlers/ApiSingleScopeHandler.cs
  Fhi.HelseId.Common/ExtensionMethods/LoggingExtensions.cs
  Fhi.HelseId.Common/Middleware/UnhandledExceptionLoggerMiddleware.cs
  Fhi.HelseId.Common/Middleware/UnhandledExceptionRedirectMiddleware.cs
  Fhi.HelseId.Web/AuthHeaderHandler.cs
  Fhi.HelseId.Web/Infrastructure/AutomaticTokenManagement/AutomaticTokenManagementConfigureCookieOptions.cs
  Fhi.HelseId.Web/Infrastructure/AutomaticTokenManagement/AutomaticTokenManagementCookieEvents.cs
  Fhi.HelseId.Web/Middleware/ProtectedPaths.cs
Labels: internal

#625 Changed to Unix-style folder seperator
  Fhi.HelseId.Web.Tests/UnitTests/HelseIdWebKonfigurasjonTests.cs
Labels: internal

#628 Ignore CS1591 for razor pages
  .editorconfig
Labels: internal

#629 Added charset = utf-8
  .editorconfig
Labels: internal

#636 Cleanup *.csproj files
  Directory.Build.props
  Fhi.AuthControllers/Fhi.AuthControllers.csproj
  Fhi.HelseId.Api.Tests/Fhi.HelseId.Api.Tests.csproj
  Fhi.HelseId.Api/CONTRIBUTORS.md
  Fhi.HelseId.Api/Fhi.HelseId.Api.csproj
  Fhi.HelseId.Blazor.Tests/Fhi.HelseId.Blazor.Tests.csproj
  Fhi.HelseId.Blazor/Fhi.HelseId.Blazor.csproj
  Fhi.HelseId.Common/Fhi.HelseId.Common.csproj
  Fhi.HelseId.Refit/Fhi.HelseId.Refit.csproj
  Fhi.HelseId.Samples/Fhi.TestFramework.Samples.csproj
  Fhi.HelseId.Swagger.Tests/Fhi.HelseId.Swagger.Tests.csproj
  Fhi.HelseId.Swagger/Fhi.HelseId.Swagger.csproj
  Fhi.HelseId.TestSupport/Fhi.HelseId.TestSupport.csproj
  Fhi.HelseId.Testframework/Fhi.TestFramework.csproj
  Fhi.HelseId.Tests/Fhi.HelseId.Tests.csproj
  Fhi.HelseId.Web.Tests/Fhi.HelseId.Web.Tests.csproj
  Fhi.HelseId.Web/CONTRIBUTORS.md
  Fhi.HelseId.Web/Fhi.HelseId.Web.csproj
Labels: internal

#637 Regenerated *.sln file
  Fhi.HelseId.sln
Labels: internal

#639 Matched folderstructure with project names
  Fhi.HelseId.Api.Tests/Fhi.HelseId.Api.Tests.csproj
  Fhi.HelseId.Web.Tests/Fhi.HelseId.Web.Tests.csproj
  Fhi.HelseId.sln
  Fhi.TestFramework.Samples/Authentication/FakeAuthenticationSamples.cs
  Fhi.TestFramework.Samples/Fhi.TestFramework.Samples.csproj
  Fhi.TestFramework.Samples/HostBuilders/Program.cs
  Fhi.TestFramework.Samples/HostBuilders/TestHostBuilderSamples.cs
  Fhi.TestFramework.Samples/HostBuilders/TestWebApplicationBuilderSamples.cs
  Fhi.TestFramework.Samples/HostBuilders/TestWebApplicationFactorySamples.cs
  Fhi.Testframework/AuthenticationSchemes/CookieAuthenticationScheme/ConfigureCookieAuthenticationOptions.cs
  Fhi.Testframework/AuthenticationSchemes/CookieAuthenticationScheme/FakeCookieManager.cs
  Fhi.Testframework/AuthenticationSchemes/CookieAuthenticationScheme/FakeCookieTicketDataFormat.cs
  Fhi.Testframework/AuthenticationSchemes/OIDCScheme/OIDCHelpers.cs
  Fhi.Testframework/AuthenticationSchemes/TestAuthenticationScheme/TestAuthenticationHandler.cs
  Fhi.Testframework/AuthenticationSchemes/TestAuthenticationScheme/TestAuthenticationSchemeOptions.cs
  Fhi.Testframework/Extensions/ClaimsIdentityExtensions.cs
  Fhi.Testframework/Extensions/HttpClientExtensions.cs
  Fhi.Testframework/Extensions/IConfigurationRootExtensions.cs
  Fhi.Testframework/Extensions/IServiceCollectionExtensions.cs
  Fhi.Testframework/Extensions/JsonSerializerExtensions.cs
  Fhi.Testframework/Extensions/TestAuthenticationExtensions.cs
  Fhi.Testframework/Fhi.TestFramework.csproj
  Fhi.Testframework/NHNTTT/Dtos/ApiException.cs
  Fhi.Testframework/NHNTTT/Dtos/ApiKey.cs
  Fhi.Testframework/NHNTTT/Dtos/ApiSpecificClaim.cs
  Fhi.Testframework/NHNTTT/Dtos/DPoPProofParameters.cs
  Fhi.Testframework/NHNTTT/Dtos/ErrorResponse.cs
  Fhi.Testframework/NHNTTT/Dtos/ExpirationParameters.cs
  Fhi.Testframework/NHNTTT/Dtos/GeneralClaimsParameters.cs
  Fhi.Testframework/NHNTTT/Dtos/HeaderParameters.cs
  Fhi.Testframework/NHNTTT/Dtos/ParametersGeneration.cs
  Fhi.Testframework/NHNTTT/Dtos/ProblemDetails.cs
  Fhi.Testframework/NHNTTT/Dtos/SuccessResponse.cs
  Fhi.Testframework/NHNTTT/Dtos/TillitsrammeverkClaimsParameters.cs
  Fhi.Testframework/NHNTTT/Dtos/TokenRequest.cs
  Fhi.Testframework/NHNTTT/Dtos/TokenResponse.cs
  Fhi.Testframework/NHNTTT/Dtos/UserClaimsParameters.cs
  Fhi.Testframework/NHNTTT/TTTService.cs
  Fhi.Testframework/NHNTTT/TokenRequestHelpers.cs
  Fhi.Testframework/WebApplicationBuilderTestHost.cs
  Fhi.Testframework/WebApplicationFactoryTestHost.cs
Labels: internal

#640 readme.md -> README.md
  Fhi.HelseId.sln
  README.md
Labels: internal

#644 Nuget/nuget upgrade
  Directory.Packages.props
Labels: dependencies

#646 Release v8.1.0
  Directory.Build.props
Labels: internal
